id = "txtar"
name = "Txtar"
version = "0.1.0"
schema_version = 1
authors = ["Tom Fleet <me@followtheprocess.codes>"]
description = "Language support for txtar files"
repository = "https://github.com/FollowTheProcess/zed-txtar"

[grammars.txtar]
repository = "https://github.com/FollowTheProcess/tree-sitter-txtar"
commit = "157687ae1ec94222d11bea4025ec880c4e0d94c5"
